import { securityData } from "./globalHelper"

const eng = {
    lang:{
        home_search_content:'Search content',
        general_view_more: 'View More',
        general_load_more_text: 'View More',
        profile_redeem_code: 'Redeem Your Code',
        home_subscribe_description: 'Get the best<br/>content every day<br/>by subscribing<br/>our newsletter !',
        home_subscribe_caption: 'Yes! I want',
        home_our_others_sources: 'Our Others Sources',
        home_submit_idea_description: 'Have no topic you’re interested in?',
        home_submit_idea_textbox:'Type your ideas here',
        header_subscribe:'Subscribe',
        home_submit_your_quite:'Click here to submit your quote',
        general_Submit:'Submit',
        general_btn_close:'Close',
        footer_contact_us:'Contact us',
        footer_feedback:'Feedback & Suggestion',
        general_no_data_available:'No data available',
        search_content_article_found:' content(s) found',
        search_content_article_not_found:'no result found',
        profile_what_do_you_wanna_learn_today:'What do you wanna learn today?',
        redeem_how_are_you_today:'How are you today ?',
        redeem_level_point_reward:'Level, point, reward',
        redeem_how_to_play:'how to play',
        redeem_your_redeemable_point:'your redeemable point',
        redeem_point:'point',
        redeem_points:'points',
        redeem_level_point:'level point',
        redeem_redeem_your_points:'Start learning, earn points and redeem with these learning support items',
        redeem_button:'Redeem',
        redeem_insufficient_points:'Insufficient Points',
        redeem_insufficient_level : 'Insufficient Level',
        redeem_unlock_level: "Finish level criteria to get reward",
        redeem_redeemed: 'Reward has been redeemed',
        redeem_limited: 'Limited Offer',
        redeem_stock_left_param_qty:'{qty} pcs left',
        redeem_out_of_stock:'out of stock',
        redeem_play:'Play',
        redeem_confirm_redeem:'Do you want to redeem [variable1] points<br/>for [variable2]?',
        redeem_success:'Thank you for redeeming your points. our friendly team will contact you<br/>for item delivery.',
        redeem_terms_conditions: "Terms and Conditions",
        general_confirm:'Confirm',
        home_show_all:'Show all',
        subscribe_confirm:'You will receive<br/>the best content information<br/>direct to your inbox !',
        subscribe_thank_you:'Thank You<br/>for subscribing!',
        subscribe_submit:'Agree!',
        submit_idea_confirm:'Thank you <br/>for your bright ideas!',
        submit_idea_short_description:'Your thoughts and feedback are much appreciated.',
        submit_idea_send_another_ideas:'Send another ideas',
        submit_course_confirm:'Thank you <br/>for your submission!',
        submit_course_send_another_ideas:'Submit another',
        are_you_sure:'You are required to complete this course before registering for another course. Are you sure about this course?',
        yes:'Yes',
        no:'No',
        choose_category:'Choose Category',
        sort_by:'SORT BY',
        sff_find_another_course:"Didn't find the course you wanted? Choose another type",
        sff_another_topic:"Another Topic",
        lang_eng:'ENG',
        lang_ind:'IND',
        submod_type1:'Video',
        submod_type2:'Article',
        submod_type3:'Article & Video',
        submod_mandatory1: 'Mandatory',
        submod_mandatory2:'Suggested',
        modules: 'Modules',
        module_for: 'Module For',
        filter_by: 'Filter By',
        progress_modules: 'Learning Progress',
        previous_exam: 'Previous Exam',
        your_score: 'Your Score',
        retake_exam: 'Retake Exam',
        take_exam: 'Take Exam',
        completed: 'Completed',
        title1: 'Let’s Open The Best',
        title2: 'Module For You',
        subtitle1: 'Now you can start studying the existing modules to expand your knowledge',
        question:'Question',
        done: 'Done',
        unfinished: 'Unfinished',
        exam_prev: 'Previous',
        exam_next:'Next Question',
        btnArticleTitleValidate: 'Share',
        btnArticleTitleUnvalidate: 'Share Anyway',
        shareArticleTitleValidate: 'Share this Content <br/>& get [variable1] points',
        shareArticleTitleUnvalidate: 'You have already shared the content',
        quizCaption: 'Read this Content <br/>& Answer the Quiz',
        quizCaptionIqos: 'Answer the question<br>iQOS Believer',
        quizPoint: 'this quiz worth [variable1] points',
        showQuiz: 'take me to the content',
        quizRules: 'Quiz will be appear below after you read the content',
        errorDate: "End date can't be earlier than start date.",
        errorCurrDate: "Date can't be earlier than current date.",
        alreadySubmitQuiz: "You have submitted this quiz.<br/>Please read and answer the other quiz",
        alertAfterShareContent: "You have successfully shared this content <br/> please share more content to your colleagues",
        alertAfterSubmitQuiz: "You got [variable1] points!<br/>thank you for your participation",
        alreadySubmitQuizIqos: "You have join the quiz before<br/><small>Thank you for your participation.</small>",
        movementIWantToLearn: "I want to learn",
        shareCourseTitleValidate: "Share this Content <br/>",
        failedRegisterCourse:"Sorry, your request could not be processed. Your learning quota has been used.<br/>",
        successRegisterCourse:"You are successfully registered. You will receive an email, follow the instruction to continue registering to the provider.<br/>",        
        successRegisterCourseNeedApprove:"For Executive Course & Certification requires Approval from the Admin side, If the Admin has agreed then there will be an email notification.<br/>",
        titleModalAttended:"Confirmation Message",
        titleModalRegisterTraining:"Registration Form Training",
        titleModalChangeScheduleTraining:"Change Schedule Form",
        titleModalConfirmRegisterTraining:"The registration process is successful, please click Save and Agree so that the Registration Status changes to <b>Registered</b>.",
        titleModalConfirmChangeScheduleTraining:"The process of changing the Training Schedule is successful, please click Save and Agree so that the Registration Status changes to <b>Registered</b>.",
        titleModalFailedConfirm:"The process cannot be carried out, because the Total Class Capacity is full. Please change to another schedule.",
        bodyModalAttended:"Are you sure you will attend the training as scheduled?",
        titleModalConfirmAttended:"The process of Save and Agree to the Training Schedule has been successful.",
        bodyModalAttended2:"I attended Training <span>[variable1]</span> ..?",
        titleModalConfirmAttended2:"The process of Save Attendance Data has been successful.",
        bodyModalChangeStatusAttend:"Are you sure you want to change your Status to <b>Attend</b> on Training [variable1] ..?",
        bodyModalChangeStatusNotAttend:"Are you sure you want to change your Status to <b>not Attend</b> on Training [variable1] ..?",
        alertAfterChangeStatus:"The Status Change Process Has Been Successful.",
        alertChooseTopic: "You have chosen the preferred topics.",
        start_learning: "Start Learning",
        select_topic: "Select topic that interests you (minimum 3 topic)",
        loading: "Please wait...",
        //newLang
        workShopButtonJoinWaitingList: "Join the waiting list",
        workShopButtonRegister: "Register",
        workShopTxtRemainingQuota: "Remaining Quota",
        workShopTxtRegisteredWaitingList: "Registered in Waiting List",
        workShopTxtRegistered: "Registered",
        workShopTxtRejected: "Rejected",
        workShopTxtProcessApproval: "Process Approval",
        workShopTxtNotFound: "WorkShop Not found",
        sharingSessionButtonJoinWaitingList: "Join the waiting list",
        sharingSessionButtonRegister: "Register",
        sharingSessionTxtRemainingQuota: "Remaining Quota",
        sharingSessionTxtRegisteredWaitingList: "Registered in Waiting List",
        sharingSessionTxtRegistered: "Registered",
        sharingSessionTxtNotFound: "Sharing Session Not found",
        workShopSharingTxtPopupRedeem: "Are you sure you will join the selected [variable1] ..?",
        workShopSharingTxtSucessRegister: "Congratulations, you have enrolled in the [variable2] [variable1]",
        // AWB 2.0
        homeBannerText: "Why it's Important<br>to Keep Learning<br>in Your Career >>>",
        wayOfLearningText: "Our Ways of<br>Learning<br>>>>",
        criticalCompetenciesText: "Core<br>Skills<br>>>>",
        planLearningText: "Plan your Learning",
        searchText: "Search",
        explore:"Explore",
        stayInTheKnowText: "Stay in<br>the know<br>>>>",
        read:"Read",
        topPicks:"top picks",
        prefferedTopic:"based on your preferred topics",
        skillsForFuture:"Skills for Future",
        latestUpdateText: "our latest update",
        chooseTheseModuleText: "choose these modules",
        confirmLearningPlan: "Are you sure to add this chosen module to your learning plan?",
        addAnotherPlan: "add another plan",
        addNewLearningPlan: "Add new learning plan",
        continueLearning: "Continue Learning",
        subTitleContinueLearning: "complete learning plan & get [variable] points",
        completedLearningPlan: "Completed Learning Plan",
        subTitleCompletedLearningPlan: "please rate the module by clicking the stars",
        seeAll:"see all",
        yourRate:"Your rate",
        rateHere: "Rate here",
        showMore:"Show more",
        showLess:"Show less",
        lastVisited: "Last visited over 30 days",
        openFullProfile:"open full profile",
        Hi:"Hi",
        profileSummary:"Profile summary",
        calendar: "Calendar",
        hereYourRecap:"Here's your RECAP",
        setYourGoal:"Set your GOAL",
        spanSetYourGoal:"We'll help you track your progress and remind you to keep learning",
        contentsWeek:"contents / week",
        addGoal:"add goal",
        editGoal:"edit goal",
        descHaveGoal:"your current progress for [variable] contents / week goal",
        learningPlan:"Learning PLAN",
        inProgress:"in progress",
        redeemablePoints:"Redeemable Points",
        contentViewed:"Content Viewed",
        badgesAchieved:"Badges Achieved",
        workshopAttended:"Workshop Attended",
        myEvents:"my events",
        today:"today",
        upcoming:"upcoming",
        workshopCapacityNoSeats:"no seat left!",
        workshopCapacityOnlyOne:"only a seat left!",
        workshopCapacityMoreThanOne:"only [x] seats left!",
        notifications:`Notifications`,
        clearAll:`clear all`,
        headerNoNotif:`Whoosh! <br/> no notifications yet!`,
        subheaderNoNotif:`we'll notify you once we have something for you!`,
        subheader2NoNotif:`Stay tuned, keep learning!`,
        registerNow:`register now`,
        moreInfo:`More info`,
        opsional:"opsional",
        category:"categories",
        years:"years",
        createNew:"create new",
        // movement page
        movementBannerText:"Why we<br>must learn?",
        movementBannerSubText:"It leads to new opportunities. It improves your productivity<br>It makes you more valuable. To make a better you",
        movementPartiesTitle:"There are<br> 3 main parties<br>that are involved",
        movementPartiesSubTitle:"We believe<br>learning needs<br>support.",
        movementPartiesPnCTitle:"People & Culture",
        movementPartiesPnCContent:"provides infrastructure for employee & people manager in self-development.",
        movementPartiesEmpTitle:"Employee",
        movementPartiesEmpContent:"responsible to have personal self-development plan creation and engaging with the people manager for checking in / asking the feedback in learning plan creation.",
        movementPartiesPMTitle:"People Manager",
        movementPartiesPMContent:"together with their team to make self-development planning, support & remind their team and conduct periodic check-in sessions related to learning progress.",
        movementLearnHelpTextTitle:"What is it?",
        movementLearnHelpTextContent:"It is a holistic way of learning in an organization by combining a combination of formal learning, from others & learning in daily work that will help your development and the organization.",
        movementLearnHeaderText:"Learning in Sampoerna",
        movementLearnCollapsibleText:"explore further",
        movement10Percent:"of Study/Self-Study",
        movement20Percent:"of Learning from Others",
        movement70Percent:"of On-The-Job Experiences",
        movement10PercentRightBar:"Study/Self-Study",
        movement20PercentRightBar:"Learning from Others",
        movement70PercentRightBar:"On-The-Job Experiences",
        movementLearnSupportSubText:"Our Solution to",
        movementLearnSupportTitleText:"Support Your Learning",
        movementLearnSupportAccessBtnText:"Access Now!",
        movementLearnSupportAbout:"About this programme",
        movementLearnSupportBenefits:"Benefits",
        movementLearnSupportTarget:"Target Participant",
        movementLearnSupportFormat:"Format",
        movementLearnSupportRegister:"No registration needed, access anytime",
        movementLearnSupportFree:"Free",
        movementLearnSupportSelfLearn:"Self Learn",
        movementLearnSupportPreWork:"tidak ada pre-work",
        movementCompManageTitle:"Core<br>Skills",
        movementCompManageSubTitle:"Look further into our",
        movementCompManageDownloadBtn:"Download full details",
        movementCompManageExploreBtn:"click any circle to explore",
        movementCompManageBackBtn:"back",
        movementCompManageLearnBtn:"Start to learn now!",
        //AWb 2.1
        challengeCard: "Challenge Card",
        courseClaim:"Claimed",
        txtPopupChooseTypeLearningPlan:"Pilih tipe learning plan yang diinginkan",
        txtPresetLearningPlan:"Preset Learning Plan",
        txtCustomLearningPlan:"Custom Learning Plan",
        txtAddNewCategoriesLearningPlan:"Add new",
        editButtonLearningPlan:"edit",
        doneButtonLearningPlan:"done",
        typeLearningPlanCoreSkills:"core skills",
        typeLearningPlanRoles:"roles",
        formLblLearningPlanName:"Your Learning Plan's Name",
        formButtonAddContent:"Add Content",
        formLblType:"type",
        formLblModule:"module",
        foromPlaceholderDropdown:"choose",
        formButtonAdd:"add",
        formButtonSubmitAll:"submit all",
        errorResetToBiggerThanFrom:"Reset level to can't bigger than reset level from",
        headerTitleLevelProgress:"Account Tiers",
        headerTitleLeaderboard:"Leaderboard",
        txtYourLevel:"You're a :",
        txtTitleGreenCard:"take the fast lane to [variable0]",
        txtBodyGreenCard:"<b>required:</b><br/>complete 3 learning plan<br/>complete 3 SFF",
        lblPopupLeaderboardName:"name",
        lblPopupLeaderboardDepartment:"title",
        lblPopupLeaderboardTierLevel:"tier level",
        lblPopupLeaderboardGroupBasetownLocation:"function",
        lblPopupLeaderboardPoints:"points",
        lblPopupLeaderboardReportTo:"report to",
        txtNavbarStartYourJourney:"Start to make your own learning plan today.",
        txtClickHere:"Click here >>>",
        courseType:"Course Type"
    }
}

const ind = {
    lang:{
        home_search_content:'Cari Konten',
        general_view_more: 'Lihat Konten Lain',
        general_load_more_text: 'Muat Lebih',
        profile_redeem_code: 'Tukar Kode Anda',
        home_subscribe_description: 'Dapatkan info<br/>konten terbaik<br/>setiap harinya hanya<br/>dengan berlangganan<br/>newsletter kami !',
        home_subscribe_caption: 'Ya! Saya mau',
        home_our_others_sources: 'Sumber Kami Lainnya',
        home_submit_idea_description: 'Tidak punya topik yang Anda suka?',
        home_submit_idea_textbox:'Ketik ide Anda di sini',
        header_subscribe:'Berlangganan',
        home_submit_your_quite:'Klik disini untuk submit quote Anda',
        general_Submit:'Kirim',
        general_btn_close:'Tutup',
        footer_contact_us:'Hubungi Kami',
        footer_feedback:'Kritik & Saran',
        general_no_data_available:'Data tidak tersedia',
        search_content_article_found:' konten ditemukan',
        search_content_article_not_found:'konten tidak ditemukan',
        profile_what_do_you_wanna_learn_today:'What do you wanna learn today?',
        redeem_how_are_you_today:'Apa kabarnya hari ini ?',
        redeem_level_point_reward:'Level, poin, hadiah',
        redeem_how_to_play:'Aturan bermain',
        redeem_your_redeemable_point:'Poin yang bisa ditukarkan',
        redeem_point:'poin',
        redeem_points:'poin',
        redeem_level_point:'Poin level',
        redeem_redeem_your_points:'Mulai belajar, dapatkan poin dan tukarkan dengan barang penunjang belajar ini',
        redeem_button:'Tukar',
        redeem_insufficient_points:'Poin Tidak Cukup',
        redeem_insufficient_level: 'Level Tidak Cukup',
        redeem_unlock_level: "Selesaikan kriteria level untuk membuka hadiah",
        redeem_redeemed: 'Sudah ditukarkan',  
        redeem_limited: 'Penawaran Terbatas',
        redeem_terms_conditions: 'Syarat dan Ketentuan',
        redeem_stock_left_param_qty:'Sisa {qty} pcs',
        redeem_out_of_stock:'Stock habis',
        redeem_play:'Bermain',
        redeem_confirm_redeem:'Apakah Anda ingin menukarkan [variable1] poin<br/>untuk [variable2]?',
        redeem_success:'Terima kasih telah menukarkan poin Anda. tim kami yang ramah akan menghubungi Anda<br/>untuk pengiriman barang.',
        general_confirm:'Setuju',
        home_show_all:'Lihat semua',
        subscribe_confirm:'Anda akan menerima info konten terbaik,<br/>langsung di email Anda!',
        subscribe_thank_you:'Terima kasih<br/>sudah berlangganan!',
        subscribe_submit:'Setuju!',
        submit_idea_confirm:'Terima kasih <br/>atas ide cemerlang Anda!',
        submit_idea_short_description:'Ide dan umpan balik Anda sangat kami hargai.',
        submit_idea_send_another_ideas:'Kirim ide lain',
        submit_course_confirm:'Terima kasih <br/>atas partisipasti anda!',
        submit_course_send_another_ideas:'Kirim dokumen lainnya',
        are_you_sure:'Anda diharuskan menyelesaikan course ini sebelum mendaftar course lain. Apakah Anda sudah yakin dengan course ini?',
        yes:'Ya',
        no:'Tidak',
        choose_category:'Pilih Kategori',
        sort_by:'ATUR BERDASARKAN',
        sff_find_another_course:"Tidak temukan course yang diinginkan? Pilih jenis lainnya",
        sff_another_topic:"Topik Lain",
        lang_eng:'ENG',
        lang_ind:'IND',
        submod_type1:'Video',
        submod_type2:'Artikel',
        submod_type3:'Artikel & Video',
        submod_mandatory1: 'Wajib',
        submod_mandatory2:'Disarankan',
        modules: 'Modul',
        module_for: 'Daftar Modul',
        filter_by: 'Filter Berdasarkan',
        progress_modules: 'Progres Pembelajaran',
        previous_exam: 'Hasil Sebelumnya',
        your_score: 'Nilai Anda',
        retake_exam: 'Ujian Lagi',
        take_exam: 'Ikutin Ujian',
        completed: 'Selesai',
        title1: 'Mari Buka Modul',
        title2: 'Yang Terbaik Untuk Anda',
        subtitle1: 'Sekarang Anda dapat mulai mempelajari modul yang ada untuk memperluas pengetahuan Anda',
        question:'Pertanyaan',
        done: 'Selesai',
        unfinished: 'Belum Selesai',
        exam_prev: 'Sebelumnya',
        exam_next:'Selanjutnya',
        btnArticleTitleValidate: 'Bagikan',
        btnArticleTitleUnvalidate: 'Bagikan saja',
        shareArticleTitleValidate: 'Bagikan konten ini<br/>& dapatkan [variable1] poin',
        shareArticleTitleUnvalidate: 'Anda sudah pernah bagikan konten ini sebelumnya',
        quizCaption: 'Lihat konten ini<br/>& jawab pertanyaanya',
        quizCaptionIqos: 'Jawab pertanyaan<br>iQOS Believer',
        quizPoint: 'Dapatkan [variable1] points jika jawabanmu benar!',
        showQuiz: 'bawa saya untuk melihat konten',
        quizRules: 'Kembali ke page ini untuk menjawab pertanyaanya',
        errorDate: "Tanggal berakhir tidak bisa lebih kecil dari tanggal mulai.",
        errorCurrDate: "Tanggal tidak bisa lebih kecil dari tanggal hari ini.",
        alreadySubmitQuiz: "Anda telah menjawab kuis ini sebelumnya.<br/>Silahkan baca dan jawab kuis lainnya",
        alertAfterShareContent: "Anda telah berhasil membagikan konten ini <br/> Mohon bagikan konten lainnya kepada rekan Anda",
        alertAfterSubmitQuiz: "Anda mendapatkan [variable1] poin !<br/>terima kasih atas partisipasi anda",
        alreadySubmitQuizIqos: "Anda sudah ikut quiz sebelumnya<br/><small>Terima kasih untuk partisipasi Anda.</small>",
        movementIWantToLearn: "Saya mau belajar",
        shareCourseTitleValidate: "Bagikan konten ini<br/>",
        failedRegisterCourse:"Maaf, permintaan Anda tidak dapat diproses. Kuota pembelajaran Anda sudah terpakai.<br/>",
        successRegisterCourse:"Anda sudah terdaftar. Anda akan mendapatkan email, ikuti petunjuk untuk melanjutkan pendaftaran ke provider.<br/>",
        successRegisterCourseNeedApprove:"Untuk Executive Course & Certification membutuhkan Approval dari sisi Admin, Jika Admin telah menyetujui maka akan ada email pemberitahuan.<br/>",
        titleModalAttended:"Pesan Konfirmasi",
        titleModalRegisterTraining:"Form Daftar di Training ",
        titleModalChangeScheduleTraining:"Form Ganti Jadwal ",
        titleModalConfirmRegisterTraining:"Proses Pendaftaran berhasil, silahkan klik Simpan dan Setuju agar Status Pendaftaran berubah menjadi <b>Terdaftar</b>.",
        titleModalConfirmChangeScheduleTraining:"Proses ubah Jadwal Training berhasil, silahkan klik Simpan dan Setuju agar Status Pendaftaran berubah menjadi <b>Terdaftar</b>.",
        titleModalFailedConfirm:"Proses tidak dapat dilakukan, dikarenakan Jumlah Kapasitas Kelas telah penuh. Silahkan ganti dengan Jadwal lainnya.",
        bodyModalAttended:"Anda yakin akan menghadiri Training sesuai Jadwal  ..?",
        titleModalConfirmAttended:"Proses Simpan dan Setuju dengan Jadwal Training telah berhasil.",
        bodyModalAttended2:"Saya menghadiri Training <span>[variable1]</span> ..?",
        titleModalConfirmAttended2:"Proses Simpan Data Kehadiran telah berhasil.",
        bodyModalChangeStatusAttend:"Apakah anda Yakin akan mengubah Status Menjadi <b>Hadir</b> pada Training [variable1] ..?",
        bodyModalChangeStatusNotAttend:"Apakah anda Yakin akan mengubah Status Menjadi <b>Tidak Hadir</b> pada Training [variable1] ..?",
        alertAfterChangeStatus:"Proses Ubah Status Telah Berhasil.",
        alertChooseTopic: "Anda telah memilih preferensi topik.",
        start_learning: "Mulai Belajar",
        select_topic: "Pilih topik yang menarik untuk anda (minimal 3 topik)",
        loading: "Mohon tunggu...",
        //newLang
        workShopButtonJoinWaitingList: "Ikut Waiting List",
        workShopButtonRegister: "Daftar",
        workShopTxtRemainingQuota: "Sisa Kuota",
        workShopTxtRegisteredWaitingList: "Terdaftar dalam Waiting List",
        workShopTxtRegistered: "Terdaftar",
        workShopTxtRejected: "Ditolak",
        workShopTxtProcessApproval: "Proses Approval",
        workShopTxtNotFound: "WorkShop Tidak ditemukan",
        sharingSessionButtonJoinWaitingList: "Ikut Waiting List",
        sharingSessionButtonRegister: "Daftar",
        sharingSessionTxtRemainingQuota: "Sisa Kuota",
        sharingSessionTxtRegisteredWaitingList: "Terdaftar dalam Waiting List",
        sharingSessionTxtRegistered: "Terdaftar",
        sharingSessionTxtNotFound: "Sharing Session Tidak ditemukan",
        workShopSharingTxtPopupRedeem: "Apakah anda yakin akan mengikuti [variable1] terpilih ..?",
        workShopSharingTxtSucessRegister: "Selamat, Anda telah terdaftar dalam [variable1] [variable2]",
        // AWB 2.0
        homeBannerText: "Mengapa Tetap Belajar<br>Sangat Penting<br>Terhadap Karir Anda >>>",
        wayOfLearningText: "Cara Kami<br>Belajar<br>>>>",
        criticalCompetenciesText: "Keterampilan<br>Inti<br>>>>",
        planLearningText: "Rencanakan Pembelajaran Anda",
        searchText: "Cari",
        explore:"Jelajah",
        stayInTheKnowText: "Tetap dalam<br>pengetahuan<br>>>>",
        latestUpdateText: "pembaruan terbaru kami",
        read:"Baca",
        topPicks:"pilihan teratas",
        prefferedTopic:"berdasarkan topik pilihan anda",
        skillsForFuture:"Skills for Future",
        chooseTheseModuleText: "pilih modul ini",
        confirmLearningPlan: "Apakah Anda yakin untuk menambahkan modul pilihan ini ke dalam rencana pembelajaran Anda?",
        addAnotherPlan: "Tambahkan rencana lain",
        addNewLearningPlan: "Tambahkan rencana pembelajaran baru",
        continueLearning: "Lanjutkan Belajar",
        subTitleContinueLearning: "Selesaikan rencana pembelajaran & dapatkan [variable] poin",
        completedLearningPlan: "Rencana Pembelajaran Selesai",
        subTitleCompletedLearningPlan: "Tolong beri nilai modul dengan mengklik bintang",
        seeAll:"Lihat semua",
        yourRate:"Rating anda",
        rateHere: "Rating disini",
        showMore:"Tampilkan lebih banyak",
        showLess:"Tampilkan lebih sedikit",
        lastVisited: "Terakhir dikunjungi selama 30 hari",
        openFullProfile:"buka profil lengkap",
        Hi:"Hai",
        profileSummary:"Ringkasan Profil",
        calendar: "Kalender",
        hereYourRecap:"Ini RECAP Anda",
        setYourGoal:"Tetapkan TUJUAN Anda",
        spanSetYourGoal:"Kami akan membantu Anda melacak kemajuan Anda dan mengingatkan Anda untuk terus belajar",
        contentsWeek:"konten / minggu",
        addGoal:"tambahkan tujuan",
        editGoal:"ubah tujuan",
        descHaveGoal:"kemajuan Anda saat ini untuk [variable] konten / tujuan minggu",
        learningPlan:"RENCANA Pembelajaran",
        inProgress:"sedang berlangsung",
        redeemablePoints:"Poin yang Dapat Ditebus",
        contentViewed:"Konten Dilihat",
        badgesAchieved:"Lencana Dicapai",
        workshopAttended:"Workshop Dihadiri",
        myEvents:"acara saya",
        today:"hari ini",
        upcoming:"mendatang",
        workshopCapacityNoSeats:"tidak ada kursi yang tersisa!",
        workshopCapacityOnlyOne:"hanya tersisa satu kursi!",
        workshopCapacityMoreThanOne:"hanya [x] kursi tersisa!",
        notifications:`Pemberitahuan`,
        clearAll:`Bersihkan semua`,
        headerNoNotif:`Whoosh! <br/> belum ada notifikasi!`,
        subheaderNoNotif:`kami akan memberi tahu Anda setelah kami memiliki sesuatu untuk Anda!`,
        subheader2NoNotif:`Tetap semangat, terus belajar!`,
        registerNow:`daftar sekarang`,
        moreInfo:`Info lebih lanjut`,
        opsional:"opsional",
        category:"kategori",
        years:"tahun",
        createNew:"membuat baru",
        // movement page
        movementBannerText:"Mengapa kita<br>harus belajar?",
        movementBannerSubText:"Belajar akan membawa Anda pada peluang baru, meningkatkan produktivitas,<br/>membuatmu menjadi lebih berharga & menjadi lebih baik.",
        movementPartiesTitle:"Ada<br> 3 pihak utama<br>yang terlibat",
        movementPartiesSubTitle:"Kami yakin<br>belajar membutuhkan<br>dukungan.",
        movementPartiesPnCTitle:"People & Culture",
        movementPartiesPnCContent:"menyediakan infrastruktur untuk karyawan & atasan dalam pengembangan diri.",
        movementPartiesEmpTitle:"Karyawan",
        movementPartiesEmpContent:"bertanggung jawab untuk membuat rencana pengembangan diri pribadi dan terlibat dengan manajer orang untuk memeriksa / meminta umpan balik dalam pembuatan rencana pembelajaran.",
        movementPartiesPMTitle:"Atasan",
        movementPartiesPMContent:"bersama-sama dengan timnya untuk membuat perencanaan pengembangan diri, mendukung & mengingatkan tim mereka serta melakukan cek berkala terkait dengan kemajuan pembelajaran.",
        movementLearnHelpTextTitle:"Apa itu?",
        movementLearnHelpTextContent:"Merupakan cara belajar yang menyeluruh dalam sebuah organisasi dengan menggabungkan kombinasi antara belajar formil, dari orang lain & belajar dalam perkerjaan sehari-hari yang akan mebantu perkembangan Anda dan organisasi.",
        movementLearnHeaderText:"Belajar di Sampoerna",
        movementLearnCollapsibleText:"jelajahi lebih lanjut",
        movement10Percent:"Belajar secara mandiri",
        movement20Percent:"Belajar dari orang lain",
        movement70Percent:"Belajar dari pengalaman",
        movement10PercentRightBar:"Belajar secara mandiri",
        movement20PercentRightBar:"Belajar dari orang lain",
        movement70PercentRightBar:"Belajar dari pengalaman",
        movementLearnSupportSubText:"Solusi kami untuk",
        movementLearnSupportTitleText:"Mendukung Pembelajaran Anda",
        movementLearnSupportAccessBtnText:"Akses Sekarang!",
        movementLearnSupportAbout:"Tentang program ini",
        movementLearnSupportBenefits:"Manfaat",
        movementLearnSupportTarget:"Target peserta",
        movementLearnSupportFormat:"Format",
        movementLearnSupportRegister:"tidak perlu registrasi, akses kapan saja",
        movementLearnSupportFree:"gratis",
        movementLearnSupportSelfLearn:"pembelajaran mandiri",
        movementLearnSupportPreWork:"tidak ada pre-work",
        movementCompManageTitle:"Keterampilan<br>Inti",
        movementCompManageSubTitle:"Lihat lebih jauh ke dalam",
        movementCompManageDownloadBtn:"Unduh detail lengkap",
        movementCompManageExploreBtn:"klik lingkaran mana saja untuk dijelajahi",
        movementCompManageBackBtn:"kembali",
        movementCompManageLearnBtn:"Mulai belajar sekarang!",
        //AWb 2.1
        challengeCard: "Kartu Tantangan",
        courseClaim:"Diklaim",
        txtPopupChooseTypeLearningPlan:"Pilih tipe learning plan yang diinginkan",
        txtPresetLearningPlan:"Preset Learning Plan",
        txtCustomLearningPlan:"Custom Learning Plan",
        txtAddNewCategoriesLearningPlan:"Add new",
        editButtonLearningPlan:"ubah",
        doneButtonLearningPlan:"selesai",
        typeLearningPlanCoreSkills:"core skills",
        typeLearningPlanRoles:"roles",
        formLblLearningPlanName:"Nama Rencana Pembelajaran Anda",
        formButtonAddContent:"Tambah konten",
        formLblType:"tipe",
        formLblModule:"modul",
        foromPlaceholderDropdown:"pilih",
        formButtonAdd:"tambah",
        formButtonSubmitAll:"kirim semua",
        errorResetToBiggerThanFrom:"Reset level to tidak bisa lebih besar dari reset level from",
        headerTitleLevelProgress:"Tingkatan Akun",
        headerTitleLeaderboard:"Leaderboard",
        txtYourLevel:"Kamu adalah :",
        txtTitleGreenCard:"ambil jalur cepat ke [variable0]",
        txtBodyGreenCard:"<b>syarat:</b><br/>menyelesaikan 3 rencana pembelajaran<br/>menyelesaikan 3 SFF",
        lblPopupLeaderboardName:"nama",
        lblPopupLeaderboardDepartment:"title",
        lblPopupLeaderboardTierLevel:"tingkat level",
        lblPopupLeaderboardGroupBasetownLocation:"function",
        lblPopupLeaderboardPoints:"poin",
        lblPopupLeaderboardReportTo:"melapor kepada",
        txtNavbarStartYourJourney:"Start to make your own learning plan today.",
        txtClickHere:"Click here >>>",
        courseType:"Tipe Course"
    }
}

const defaultLang = securityData.Security_lang()? 
                {
                    'ENG' : eng,
                    'IND' : ind
                }[securityData.Security_lang()] || eng
            : 
            eng

export default defaultLang;